### ISSUE TITLE
セレクタ間の空白について

### ISSUE THREAD

**Issue by pipupika** [pipupika/modenCoding#1]
```
    <header class="header">
      <h1 class="logo">
        <a href="/">SAMPLE SITE</a>
      </h1>
      <nav class="global-nav">
        <ul>
          <li class="nav-item active"><a href="#">HOME</a></li>
          <li class="nav-item"><a href="#">NEWS</a></li>
          <li class="nav-item"><a href="#">TOPICS</a></li>
          <li class="nav-item"><a href="#">DOCS</a></li>
          <li class="nav-item"><a href="#">BLOG</a></li>
        </ul>
      </nav>
    </header>
```
```

.global-nav .nav-item{
  display: inline-block;
  margin: 0 10px;
}

```
なぜここは.global-navを設定するんですか？　
.nav-itemだけ入れるのかなと思ったんですが、それじゃだめな理由を知りたいです。
少し調べたんですが、子孫セレクタ？というやつですか…？

**Comment by izakikazuho** [comment]
@pipupika 
お疲れ様です。

> 子孫セレクタ？というやつですか

まずこれ、大正解です！
この場合、`.global-nav`の全ての子孫要素から`.nav-item`のクラスがついた要素を探し出してスタイルを適用するという挙動になります。
他にも、子セレクタや隣接セレクタと言った昨日はよく使うので、調べておくと便利かも！

で、**なぜ今回このような指定の仕方をするのか**なんですが、これはCSSの設計と大きく関わります。
課題サイトの完成ソースを見ていないのであくまで推測なのですが、`.nav-item`という名前は極めて普遍的な命名で、他の箇所にも登場する可能性がありそうです。
サイト内でナビゲーションと名付けるべきパーツは、グローバルナビゲーション以外にもたくさん存在し得るのです。
（例：フッターのナビゲーション、サイドバーのナビゲーション、ページごとのローカルナビゲーション、パンくずリストなど）

それぞれの役割が重複することはあまり無いのですが、マークアップの構造自体は大体同じになることがほとんど。
となると、それぞれのナビゲーションの項目要素にも`.nav-item`と命名したくなるのではないでしょうか。

今はヘッダーのスタイルしか書いてないので、おっしゃる通り`.nav-item`に対してスタイリングしても問題は起こりません。
しかし、いざ他の箇所でナビゲーションを実装しようとした時に、同様に`.nav-item`と命名してしまうと。。おわかりですよね。

すでにグロナビ用のスタイリングがされてしまっている！！もう一度`.nav-item`に対して新しいスタイルを書く！！あれ！！今度はグロナビの`.nav-item`が上書きされて崩れた！！

という現象が起こります。

それを避けるために、〇〇ナビの中にある`.nav-item`と、CSSが適用される範囲を指定してあげたのが今回の例です。

ただ、昨今のCSS設計界隈（様々な宗派があるので一概には言えない）では、このような名前の重複をそもそも禁じて、意図せぬスタイルの上書きを防ぐ考え方が一般的です。
具体的には、クラス名の命名をルール化して、長くて一意なモノにする。
今回の場合だと、`.global-nav__item`のように、要素が属するコンポーネントの名前を先頭に配することで、名前の重複を防ぎます。
課題をやるにおいては、今はそこまで意識する必要はないと思うんですが、興味があったら調べてみると面白いです。

日本の開発現場でかなり一般的なFLOCSSのドキュメント
https://github.com/hiloki/flocss

難しいかもなので、噛み砕いた記事も併せて。
https://www.tam-tam.co.jp/tipsnote/html_css/post10205.html

**Comment by pipupika** [comment]
回答ありがとうございます！（返信遅くなってすみません！）

子孫セレクタが必要な意味がわかりました！
CSSが複雑になればなるほど、命名規則であったりどう作るのかを意識しないとこんがらがっちゃうんですね。
隣接セレクタは調べてみたんですが、イマイチ使いどころがわからなかったので、また質問させていただくかもです！

命名規則についての記事もありがとうございました。
読んでてなんとなくわかったようなわからないような…という理解度です。
いま時点ではこういうものもあるんだというぐらいの認識で頭に入れておきます！
