### ISSUE TITLE
display: block; 時の text-align の扱い

### ISSUE THREAD

**Issue by pipupika** [pipupika/modenCoding#2]
```
.article-box .date{
  position: absolute;
  right: 0;
  bottom: 15px;
  display: block;
  width: 160px;
  padding: 4px;
  background-color: #b5d264;
  color: #2d3d54;
  text-align: center;
  letter-spacing: 1px;
  font-weight: bold;
  font-size: 1.1rem;
}
```
`display: block;`のときは`text-align`が指定できないはずですが、なぜこれはできているのでしょうか？

**Comment by izakikazuho** [comment]
@pipupika 
> display: block;のときはtext-alignが指定できない

この解釈、とても惜しい！！
text-alignというのは、指定した要素それ自体の配置を決めるわけではなく、**その子要素/テキストノードの配置について決めるもの**なのです。
そしてその子要素というのは、inline要素、inline-blockを指定した要素が対象で、blockが指定された要素はその配置の対象にはならない。「display: block;のときはtext-alignが指定できない」というのはこういうことです。

なので今回の場合は、`.article-box .date` **の子要素、または含まれるテキストの配置を中央とするため**  に、text-align: centerと指定しています。

https://developer.mozilla.org/ja/docs/Web/CSS/text-align

**Comment by pipupika** [comment]
なるほど！
今回の質問箇所は、この画像の日付の部分の話なんですが、「`.display: block;`は緑のboxのpaddingを指定するためにおいて、`.text-align: center;`は文字のみにかかっている」ということですね。
![image](https://user-images.githubusercontent.com/66509598/92180893-0af24f00-ee83-11ea-866a-1da8a5f7aa8b.png)
