### ISSUE TITLE
class名の空白について

### ISSUE THREAD

**Issue by pipupika** [pipupika/modenCoding#3]
```
        <ul class="scroll-list">
          <li class="scroll-item">
            <a href="#">
              <time class="date" datetime="2015-08-23">2015.08.23 SUN</time>
              <span class="category news">NEWS</span>
              <span class="title">WOEKSを更新しました。</span>
            </a>
          </li>
          /*省略*/
        </ul>
```
```
.scroll-list .category.news{
  background-color: #2c3c53;
}
```
` class="category news"`は「category news」で一つのクラス名だと思っていましたが、CSSでは`.category.news`と2つ指定されています。
` class="category news"`の空白はどういう意味を持つのでしょうか？

**Comment by izakikazuho** [comment]
@pipupika 
HTMLにおいて、クラス属性には複数のクラスを指定することができて（マルチクラスという）、その場合はクラスとクラスの間を半角スペースで分かつ決まりになっています。逆に、半角スペースを含むクラス名は指定できないとも言えるので注意。
今回の場合は、.categoryに対して、どのカテゴリーの項目でも共通のスタイル（おそらくフォントサイズやボーダーなどの装飾）を指定して、.newsに対しては、newsというカテゴリー固有のスタイル（色）を指定しています。使いまわせるベーシックなスタイルは使いまわしつつ、そこから枝分かれの派生パターンを作っていくイメージかと思います。
命名規則は違うけれど、CSSのネーミングパターンでいうmodifierの概念です。

https://qiita.com/usagi-f/items/b4e56e765384c49d5d04

**Comment by pipupika** [comment]
@izakikazuho 

> 使いまわせるベーシックなスタイルは使いまわしつつ、そこから枝分かれの派生パターンを作っていくイメージかと思います。

これめっちゃイメージしやすかったです！ありがとうございます！
CSSで書くときは枝だけじゃなくて幹も書くルールという認識で合ってますか？
category=幹、news=枝

**Comment by izakikazuho** [comment]
@pipupika 今回の設計ではそうですね。幹 枝とすると子孫セレクタとして適用されるので、自ずとスタイルの適用範囲が絞られることを利用した設計。

**Comment by pipupika** [comment]
理解しました！ありがとうございます！
