### ISSUE TITLE
隣接セレクタの影響範囲について

### ISSUE THREAD

**Issue by pipupika** [pipupika/modenCoding#4]
```
        <ul class="documents">
          <li>
            <h3 class="title">HTML5</h3>
            <ul>
              <li><a href="#">追加された要素</a></li>
              <li><a href="#">削除された要素</a></li>
              <li><a href="#">意味が変わった要素</a></li>
              <li><a href="#">HTML5のコンテンツモデル</a></li>
            </ul>
          </li>
```
```
.documents > li + li{
  margin-top: 25px;
}

```

> これは隣接セレクタといい、ある要素と隣接して直後に続く要素を表します。.documents > li + liの場合は「.documents > li のあとに続く li」なので、.document直下にあるliのうち２つ目以降のliに対して適用されます。

隣接セレクタに関して質問です。
本ではこの引用のように書かれていたのですが、隣接セレクタは直後にあるものだけなので、ここで言う「追加された要素」だけに反映されるのでは？と思っています。
なぜ違うのでしょうか？
また.`documents > li > li`だとだめな理由も教えていただきたいです！

**Comment by izakikazuho** [comment]
隣接セレクタ、難しいすよね。

さて、今回のこのスタイルの目的はなんでしょう？
![image](https://user-images.githubusercontent.com/25450716/93506356-1bacc580-f957-11ea-8276-d398f56d5256.png)
一つ一つの項目ごとのマージンは別で定義するけど、カテゴリごとのまとまりの二番目以降にマージンを付けたい。
これを実現するにはいろいろ方法があります。例えば(.documents > li:nth-child(n + 2))とか、margin-botttomを与えたい場合は(.documents > li:last-child)だけマージンをとるするとか。あるいは、普通にマージンが不要な要素にだけmodifierクラスを与えるとか。

今回の隣接セレクタを使った方法はかなりスマートな方法です。すなわち、同じ階層にあるli要素に続く全てのli要素にmargin-topを与える。liに続かなくなった瞬間に命は途絶えます。

>「ある要素と隣接して直後に続く要素」

これを一つずつ噛み砕きましょう。

まず、ここでいうある要素とは、`.documents > li`を指します。これは子セレクタなので、`.documents`の直下、つまり孫要素を含まない全ての`li`。２行目のそれです。

![image](https://user-images.githubusercontent.com/25450716/93504599-a8a24f80-f954-11ea-8b33-e0b1c0cbeaf7.png)

で、例の隣接セレクタ。この場合は、２行目のliと同じ階層にある、直後のliです。
引用されたコードには入っていない部分ですね。

liに続くliという条件でセレクトされるのですが、今回の場合は、.documentsの子要素と適用範囲を絞っているので、さらに子要素で同条件に引っかかりそうなものでもセレクトされないわけです。

テクニカルですね。
最初は写経でもいいんだけど、もう少し、このコードをどんな目的で書いているのかを意識してみると楽しめると思います！

ちなみに、`.documents > li > li` だと多分どの要素にもスタイルを適用できないと思います。
さあ、それはどうしてでしょうか。クイズです。

**Comment by pipupika** [comment]
なるほど、やっと理解しました。
いざきさんの図解のおかげでこのリストの箱の中の仕組みがなんとなくわかりました。

> ちなみに、.documents > li > li だと多分どの要素にもスタイルを適用できないと思います。

これは、.document > li の直下にli要素がないため、どこにも適用されないのかなと思いました！
子セレクタは孫要素にはかからないので、`.documents > li > li `だとどこにもかからない。
`.documents > li  li `だと孫要素にもかかるので、`.document > li > ul > li`とおなじところにスタイルを適用できる。
という認識です！あっていますか？

**Comment by izakikazuho** [comment]
@pipupika 
大正解！

**Comment by pipupika** [comment]
よっし！ありがとうございます！
