### ISSUE TITLE
フッターの右寄せについて

### ISSUE THREAD

**Issue by pipupika** [pipupika/modenCoding#5]
```
    <footer class="footer">
      <ul class="horizontal-list">
        <li class="horizontal-item"><a href="#">ABOUT ME</a></li>
        <li class="horizontal-item"><a href="#">SITE MAP</a></li>
        <li class="horizontal-item"><a href="#">SNS</a></li>
        <li class="horizontal-item"><a href="#">COTACT</a></li>
      </ul>
      <p class="copyright">Copyright © 2015 SAMPLE SITE</p>
    </footer>
```
```
.horizontal-list{
  width: 970px;
  margin: 0 auto;
  text-align: right;
  font-size: 0;
}
```
なぜ`margin: 0 auto;`をしてから`text-align: right;`をするのでしょうか？
右寄せしたいのであれば`margin: 0 auto;`が不必要なのではと思いました。
実際に`margin: 0 auto;`を取ると中央寄せになってしまいました。
なぜこうなるのかを教えていただきたいです！

**Comment by izakikazuho** [comment]
@pipupika 
これは、issue #2 の内容に関連するんだけれど、単に「中央寄せにする」「右寄せにする」という言葉で捉えずに、何がどういう仕組みでそういうレイアウトになっているのかを常に考え続けることが大事です。

今回の場合、**コンテンツ幅を970pxと仕様として定めている**ので、装飾などを除く全ての情報はその範囲内に収める必要があります。
おっしゃる通り、`.horizonatal-list` に`text-align: right` を指定するだけでも右寄せにはなりますが、それだとコンテンツ幅に収まらないと思いませんか？試しに、`.horizonatal-list`のwidthの指定を外してみてください。
今回やりたいことは、コンテンツ幅の範囲内での右寄せです。そのためには、`.horizontal-list`の幅にコンテンツ幅を指定しますね。しかし、それだけでは、970pxの中では右寄せになるけれど、970pxの見えない箱が、画面内で左にくっついてしまいます。
`margin: 0 auto`はブロック要素**自身**を左右中央に配置するテクニックです。これを指定することで、970pxの見えない箱を画面の中央に配置することができますね。こうした組み合わせで、 **「コンテンツ幅内でのテキスト右寄せ」** が実現するわけです。

![image](https://user-images.githubusercontent.com/25450716/93502065-35e3a500-f951-11ea-8464-30c931ca7138.png)
![image](https://user-images.githubusercontent.com/25450716/93502092-4005a380-f951-11ea-827d-fad829bff01c.png)

予想外の配置になってしまった時は、Chromeの検証ツールで一つ一つのスタイルの利き方を見ることで理解が深まります。
実際の開発でもこれを開かない日はないし、勉強にもなるので、是非活用してください。
https://qiita.com/d-dai/items/0b580b26bb1d1622eb46

**Comment by pipupika** [comment]
教えていただきありがとうございます！
  `margin: 0 auto;`  `text-align: right;`それぞれ、掛かっている場所がぜんぜん違うことがわかりました。
疑問に思っていることは検証ツールで解決しそうなので、自分で確認してから質問を投げようと思います。
